apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: test-sa
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
rules:
- "apiGroups":
  - "*"
  "resourceNames": null
  "resources":
  - "*"
  "verbs":
  - "*"
- "apiGroups":
  - "security.openshift.io"
  "resourceNames":
  - "turbonomic-t8c-operator-anyuid"
  "resources":
  - "securitycontextconstraints"
  "verbs":
  - "use"

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: test-sa
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: test-sa
subjects:
- kind: ServiceAccount
  name: test-sa
  namespace: gitops-service-account
---
