apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitops-service-account-test-sa-sa
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: gitops-service-account
    server: https://kubernetes.default.svc
  project: 1-infrastructure
  source:
    path: payload/1-infrastructure/namespace/gitops-service-account/test-sa-sa
    repoURL: https://github.com/cloud-native-toolkit-test/gitops-service-account.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  ignoreDifferences:
    - jsonPointers:
        - /imagePullSecrets
        - /secrets
      kind: ServiceAccount
